name: "Enforce data-migration label"
on:
  pull_request_target:
    types: [unlabeled]

jobs:
  enforce_labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: tspascoal/get-user-teams-membership@v2
      with:
        username: ${{ github.actor }}
        team: 'back-end-code-owners'
        GITHUB_TOKEN: ${{ secrets.CO1_AUTO_APPROVE_TOKEN }} # needs org:read permission
    - uses: actions/labeler@v4
      if: ${{ github.event.action == 'unlabeled' && github.event.label.name == 'data migration' && steps.checkUserMember.outputs.isTeamMember == 'false' }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"




