name: "Enforce data-migration label"
on:
  pull_request_target:
    types: [unlabeled]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      if: ${{ github.event.action == "deleted" && github.event.label.name == "data migration" }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"




